---
title: "Plotly"
author: "Muhire Honorine Kwizera"
date: "11/1/2017"
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
library(readr)
library(janitor)
library(stringr)
library(forcats)
library(viridis)

library(plotly) # for plotly
```

```{r}
airbnb_data = 
  read_csv("./data/nyc_airbnb.zip") %>%
  # preparing data for plotting
  clean_names() %>%
  mutate(rating = review_scores_location / 2) %>%
  select(boro = neighbourhood_group, neighbourhood, rating, price, room_type,
         latitude, longitude) %>%
  filter(!is.na(rating),
         boro == "Manhattan",
         room_type == "Entire home/apt",
         price %in% 100:400)  %>% 
  sample_n(5000)
```

Using plotly

* scatterplot
```{r}
airbnb_data %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~text_label)
```

* box plot

```{r}
common_neighborhoods =
  airbnb_data %>% 
  count(neighbourhood, sort = TRUE) %>%
  top_n(8) %>%
  select(neighbourhood)
## Selecting by n

inner_join(airbnb_data, common_neighborhoods,
             by = "neighbourhood") %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>%
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "Set2")
```

* bar graph

```{r}
airbnb_data %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

* **ggplottly** to turn ggplot into a plotly. This can also be done for a box plot

```{r}
scatter_ggplot = airbnb_data %>%
  ggplot(aes(x = longitude, y = latitude, color = price)) +
  geom_point(alpha = 0.25) +
  scale_color_viridis() +
  coord_cartesian() +
  theme_classic()

ggplotly(scatter_ggplot)
```

